//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class КомпьютернаяФирмаEntities : DbContext
    {
        public КомпьютернаяФирмаEntities()
            : base("name=КомпьютернаяФирмаEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ВидКомплектующих> ВидКомплектующих { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Заказчик> Заказчик { get; set; }
        public virtual DbSet<Комплектующее> Комплектующее { get; set; }
        public virtual DbSet<ПослужнойСписок> ПослужнойСписок { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<СписокКомплектующих> СписокКомплектующих { get; set; }
        public virtual DbSet<СписокУслуг> СписокУслуг { get; set; }
        public virtual DbSet<Услуга> Услуга { get; set; }
        public virtual DbSet<ВсеЗаказы> ВсеЗаказы { get; set; }
        public virtual DbSet<ВсеКомплектующие> ВсеКомплектующие { get; set; }
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
    }
}
