//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ASP.Models
{
    using System;
    using System.Collections.Generic;

    public partial class ВсеЗаказы
    {
        [DisplayName("Заказ")]
        public int КодЗаказа { get; set; }
        public string Заказчик { get; set; }
        public string Сотрудник { get; set; }
        [DisplayName("Дата заказа")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]    
        public Nullable<System.DateTime> ДатаЗаказа { get; set; }
        [DisplayName("Дата исполнения")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]    
        public Nullable<System.DateTime> ДатаИсполнения { get; set; }
        public Nullable<double> Предоплата { get; set; }
        [DataType(DataType.MultilineText)]
        public string Отметки { get; set; }
        public Nullable<int> Гарантия { get; set; }
        [DataType(DataType.Currency)]
        public Nullable<double> Стоимость { get; set; }
    }
}
