//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public int КодЗаказа { get; set; }
        public Nullable<System.DateTime> ДатаЗаказа { get; set; }
        public Nullable<System.DateTime> ДатаИсполнения { get; set; }
        public int КодЗаказчика { get; set; }
        public Nullable<double> Предоплата { get; set; }
        public string Отметки { get; set; }
        public Nullable<int> Гарантия { get; set; }
        public int КодСотрудника { get; set; }
        public Nullable<double> Стоимость { get; set; }
    }
}
