//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПослужнойСписок
    {
        public int КодСписка { get; set; }
        [DisplayName("Должность")]
        public int КодДолжности { get; set; }
        [DisplayName("Сотрудник")]
        public int КодСотрудника { get; set; }
        [DisplayName("Дата назначения")]
        public Nullable<System.DateTime> ДатаНазначения { get; set; }
        [DisplayName("Дата освобождения")]
        public Nullable<System.DateTime> ДатаОсвобождения { get; set; }
    
        public virtual Должность Должность { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
