//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуга
    {
        public Услуга()
        {
            this.СписокУслуг = new HashSet<СписокУслуг>();
        }
    
        public int КодУслуги { get; set; }
        [DisplayName("Наименование услуги")]
        public string Наименование { get; set; }
        [DataType(DataType.MultilineText)]
        public string Описание { get; set; }
        [DataType(DataType.Currency)]
        public Nullable<double> Стоимость { get; set; }
    
        public virtual ICollection<СписокУслуг> СписокУслуг { get; set; }
    }
}
